### ISSUE TITLE
some bug

### ISSUE THREAD

**Issue by 0327qian** [SnowzTail/rate-splitting-multiple-access-for-downlink-communication-systems#1]
错误使用 matlab.internal.webservices.HTTPConnector/copyContentToByteArray
服务器返回了状态 401 和消息 ""，以响应对 URL https://api.pushbullet.com/v2/pushes 的请求。

**Comment by snowztail** [comment]
Please comment out all lines containing `Push` and `Pushbullet`.

Those are used to monitor the runtime status and send notifications via Pushbullet APIs.
